name: MRA Alternatives Validation

on: [push, pull_request, workflow_dispatch]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate with MRA checker script
      shell: bash
      run: |
        set -euo pipefail
        MRA_CHECKER_SCRIPT_URL=${MRA_CHECKER_SCRIPT_URL:-"https://raw.githubusercontent.com/MiSTer-devel/Scripts_MiSTer/master/other_authors/mra_rom_check.sh"}
        echo "${MRA_CHECKER_SCRIPT_URL}"
        curl --fail --location -o checker.sh "${MRA_CHECKER_SCRIPT_URL}"
        chmod +x checker.sh
        ./checker.sh --mra-folder _alternatives --recursive --ignore-roms
      env:
        MRA_CHECKER_SCRIPT_URL: ${{ secrets.MRA_CHECKER_SCRIPT_URL }}
